//
//  LLMAdviceService.swift
//  food2fit
//
//  Service for generating personalized fitness advice using LLM
//

import Foundation

/// Personalized advice generated by LLM
struct FitnessAdvice: Codable {
    let summary: String
    let exerciseSuggestions: [String]
    let mealSuggestions: [String]
    let healthTips: [String]
    let motivationalMessage: String
}

/// Service for generating personalized fitness advice
final class LLMAdviceService {
    
    static let shared = LLMAdviceService()
    
    private var apiKey: String?
    private var apiEndpoint: String = "https://api.openai.com/v1/chat/completions"
    private var modelName: String = "gpt-4o-mini"
    
    private init() {}
    
    /// Configure the API service
    func configure(apiKey: String, endpoint: String? = nil, model: String? = nil) {
        self.apiKey = apiKey
        if let endpoint = endpoint {
            self.apiEndpoint = endpoint
        }
        if let model = model {
            self.modelName = model
        }
    }
    
    /// Generate personalized fitness advice based on meal and user profile
    /// - Parameters:
    ///   - foodItems: List of recognized food items
    ///   - totalCalories: Total calories in the meal
    ///   - userWeight: User's weight in kg
    ///   - fitnessGoal: User's fitness goal
    /// - Returns: Personalized FitnessAdvice
    func generateAdvice(
        foodItems: [String],
        totalCalories: Int,
        userWeight: Double,
        fitnessGoal: FitnessGoal
    ) async throws -> FitnessAdvice {
        
        // If API key is configured, use LLM
        if let apiKey = apiKey, !apiKey.isEmpty {
            return try await fetchAdviceFromLLM(
                foodItems: foodItems,
                totalCalories: totalCalories,
                userWeight: userWeight,
                fitnessGoal: fitnessGoal,
                apiKey: apiKey
            )
        }
        
        // Fallback to local advice generation
        return generateLocalAdvice(
            foodItems: foodItems,
            totalCalories: totalCalories,
            userWeight: userWeight,
            fitnessGoal: fitnessGoal
        )
    }
    
    /// Fetch advice from LLM API
    private func fetchAdviceFromLLM(
        foodItems: [String],
        totalCalories: Int,
        userWeight: Double,
        fitnessGoal: FitnessGoal,
        apiKey: String
    ) async throws -> FitnessAdvice {
        
        let foodList = foodItems.joined(separator: ", ")
        
        let prompt = """
        You are a fitness and nutrition coach. Based on the following meal information and user profile, provide personalized advice.
        
        Meal: \(foodList)
        Total Calories: \(totalCalories) kcal
        User Weight: \(userWeight) kg
        Fitness Goal: \(fitnessGoal.rawValue)
        
        Provide advice in the following JSON format only, without any markdown or additional text:
        {
            "summary": "Brief 1-2 sentence summary of the meal's impact",
            "exerciseSuggestions": ["suggestion 1", "suggestion 2", "suggestion 3"],
            "mealSuggestions": ["healthier alternative 1", "healthier alternative 2"],
            "healthTips": ["tip 1", "tip 2"],
            "motivationalMessage": "Encouraging message"
        }
        """
        
        let requestBody: [String: Any] = [
            "model": modelName,
            "messages": [
                ["role": "system", "content": "You are a helpful fitness coach that returns only JSON data."],
                ["role": "user", "content": prompt]
            ],
            "temperature": 0.7,
            "max_tokens": 600
        ]
        
        guard let url = URL(string: apiEndpoint) else {
            throw NutritionAPIError.networkError("Invalid API endpoint")
        }
        
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue("Bearer \(apiKey)", forHTTPHeaderField: "Authorization")
        request.httpBody = try JSONSerialization.data(withJSONObject: requestBody)
        
        let (data, response) = try await URLSession.shared.data(for: request)
        
        guard let httpResponse = response as? HTTPURLResponse,
              httpResponse.statusCode == 200 else {
            throw NutritionAPIError.networkError("API request failed")
        }
        
        guard let json = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              let choices = json["choices"] as? [[String: Any]],
              let firstChoice = choices.first,
              let message = firstChoice["message"] as? [String: Any],
              let content = message["content"] as? String,
              let adviceData = content.data(using: .utf8) else {
            throw NutritionAPIError.parsingError("Could not parse API response")
        }
        
        return try JSONDecoder().decode(FitnessAdvice.self, from: adviceData)
    }
    
    /// Generate advice locally when offline or API unavailable
    private func generateLocalAdvice(
        foodItems: [String],
        totalCalories: Int,
        userWeight: Double,
        fitnessGoal: FitnessGoal
    ) -> FitnessAdvice {
        
        let runningMinutes = ExerciseType.running.minutesToBurn(calories: totalCalories, weightKg: userWeight)
        let walkingMinutes = ExerciseType.walking.minutesToBurn(calories: totalCalories, weightKg: userWeight)
        
        var summary: String
        var exerciseSuggestions: [String]
        var mealSuggestions: [String]
        var healthTips: [String]
        var motivationalMessage: String
        
        // Customize based on calorie level
        if totalCalories < 300 {
            summary = "This is a light meal with \(totalCalories) calories. Good choice for maintaining balance!"
            exerciseSuggestions = [
                "A \(runningMinutes)-minute jog would burn these calories",
                "Or enjoy a \(walkingMinutes)-minute walk",
                "This meal can be balanced with your regular activity"
            ]
            healthTips = [
                "Light meals help maintain stable energy levels",
                "Consider pairing with protein for satiety"
            ]
            motivationalMessage = "Great portion control! Keep making mindful choices."
            
        } else if totalCalories < 600 {
            summary = "A moderate meal with \(totalCalories) calories - a typical lunch or dinner portion."
            exerciseSuggestions = [
                "\(runningMinutes) minutes of running to burn these calories",
                "\(walkingMinutes) minutes of brisk walking",
                "A 30-minute mixed cardio workout would cover most of this"
            ]
            healthTips = [
                "Moderate portions are key to sustainable eating",
                "Stay hydrated throughout the day"
            ]
            motivationalMessage = "Balance is key! Enjoy your meal and stay active."
            
        } else {
            summary = "This is a hearty meal with \(totalCalories) calories - consider it a treat or post-workout fuel."
            exerciseSuggestions = [
                "\(runningMinutes) minutes of running needed",
                "Consider splitting into two exercise sessions",
                "A one-hour workout class would help offset this"
            ]
            healthTips = [
                "Higher calorie meals are fine occasionally",
                "Try to balance with lighter meals the rest of the day",
                "Increase water intake after heavy meals"
            ]
            motivationalMessage = "Enjoy it guilt-free! Tomorrow is a new day to stay active."
        }
        
        // Customize meal suggestions based on fitness goal
        switch fitnessGoal {
        case .weightLoss:
            mealSuggestions = [
                "Try grilled options instead of fried",
                "Add more vegetables for fiber and fullness",
                "Consider smaller portions with more protein"
            ]
        case .muscleGain:
            mealSuggestions = [
                "Ensure adequate protein in each meal",
                "Don't skip carbs - they fuel your workouts",
                "Consider a protein shake as supplement"
            ]
        case .maintenance:
            mealSuggestions = [
                "Keep meals balanced with all macronutrients",
                "Maintain consistent meal timing",
                "Listen to your hunger cues"
            ]
        case .generalHealth:
            mealSuggestions = [
                "Include colorful vegetables for variety",
                "Choose whole grains when possible",
                "Limit processed foods"
            ]
        }
        
        return FitnessAdvice(
            summary: summary,
            exerciseSuggestions: exerciseSuggestions,
            mealSuggestions: mealSuggestions,
            healthTips: healthTips,
            motivationalMessage: motivationalMessage
        )
    }
}
